=== jCoderZ/fawkez-old/src/xml/dtd/report.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE report SYSTEM "report.dtd">

    <report>
    ...
    </report>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT item EMPTY>
<!ATTLIST item
    message CDATA #IMPLIED
    severity ( info | warning | error | coverage ) "info"
    type ( pmd | checkstyle | findbugs | coverage ) #REQUIRED
    counter CDATA #IMPLIED
    column CDATA #IMPLIED
    end-column CDATA #IMPLIED
    line CDATA #IMPLIED
    end-line CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT file (item)*>
<!ATTLIST file
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT report (file)*>

=== jCoderZ/fawkez-old/src/xml/report_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report SYSTEM "report.dtd">

<report>
   <file name="d:/home/phoenix/phoenix/src/java/org/jcoderz/phoenix/report/Java2Html.java">
      <item line="8"
            column="1"
            severity="info"
            message="Utility classes should not have a public or default constructor."
            end-line="125"
            end-column="80"
            type="pmd"/>
      <item line="9"
            column="1"
            severity="info"
            message="Utility classes should not have a public or default constructor."
            end-line="125"
            end-column="80"
            type="pmd"/>
      <item line="10"
            column="1"
            severity="info"
            message="Utility classes should not have a public or default constructor."
            end-line="125"
            end-column="80"
            type="pmd"/>
      <item line="10"
            column="7"
            severity="error"
            message="Utility classes should not have a public or default constructor."
            end-line="125"
            end-column="80"
            type="checkstyle"/>
      <item line="11"
            column="1"
            severity="info"
            message="Utility classes should not have a public or default constructor."
            end-line="125"
            end-column="80"
            type="pmd"/>
      <item line="14"
            end-line="125"
            severity="info"
            counter="0"
            message="Utility classes should not have a public or default constructor."
            type="pmd"/>
      <item line="51"
            counter="10"
            type="coverage"/>
      <item line="52"
            counter="10"
            type="coverage"/>
      <item line="53"
            counter="10"
            type="coverage"/>
      <item line="57"
            counter="0"
            type="coverage"/>
   </file>
</report>
